*** Settings ***
Resource        ../Resources/PageObjects/Common.resource
Resource        ../Resources/PageObjects/LoginPage.resource
Library         DataDriver    file=../Resources/Data/login.xlsx    sheet_name=Sheet1

Test Setup      Mo Trinh Duyet QNU
Test Teardown   Dong Trinh Duyet QNU
Test Template   Template Dang Nhap QNU

*** Test Cases ***
Dang nhap cho nhieu tai khoan bang file Excel    # Tên này sẽ được thay thế bằng tên trong file Excel
    [Documentation]    Generated by DataDriver
*** Keywords ***
Template Dang Nhap QNU
    [Arguments]    ${username}    ${password}
    Di Toi Trang Dang Nhap
    Nhap Tai Khoan    ${username}
    Nhap Mat Khau     ${password}
    Click Nut Dang Nhap
    Kiem Tra Dang Nhap Thanh Cong